version: "3"

services:
  electrs:
    image: waltersouto/electrs:${TAG}@sha256:2525f3111421f5e1463379159ca4c135ecad40b1853e7e0c5bc0f00f32e02da9
    restart: "no"
    ports:
      - "${HOST_PORT}:50001"
    volumes:
      - "${HOST_DATA_DIR}:/data"
      - "${HOST_BTC_DIR}:${DAEMON_DIR}:ro"
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "bitcoin"
      ELECTRS_SERVER_BANNER: "${BANNER}"
      ELECTRS_DAEMON_RPC_ADDR: "${BTC_ADDR}:${BTC_RPC_PORT}"
      ELECTRS_DAEMON_P2P_ADDR: "${BTC_ADDR}:${BTC_P2P_PORT}"
      ELECTRS_ELECTRUM_RPC_ADDR: "${HOST_ADDR}:${HOST_PORT}"
      ELECTRS_DAEMON_DIR: "${DAEMON_DIR}"
      ELECTRS_DB_DIR: "${DB_DIR}"
