version: "3"

services:
  electrs:
    image: waltersouto/electrs:${TAG}@sha256:a34b93331ae7afb9ba3dad42f0318ce7530c47b6a7c09fdc5f1184fbc7238d51
    restart: "no"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "${HOST_DATA_DIR}:/data"
      - "${HOST_BTC_DIR}:${DAEMON_DIR}:ro"
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "bitcoin"
      ELECTRS_SERVER_BANNER: "${BANNER}"
      ELECTRS_DAEMON_RPC_ADDR: "${BTC_ADDR}:${BTC_RPC_PORT}"
      ELECTRS_DAEMON_P2P_ADDR: "${BTC_ADDR}:${BTC_P2P_PORT}"
      ELECTRS_ELECTRUM_RPC_ADDR: "${ADDR}:${PORT}"
      ELECTRS_DAEMON_DIR: "${DAEMON_DIR}"
      ELECTRS_DB_DIR: "${DB_DIR}"

